#--------------------------------------------------
# Site settings
#--------------------------------------------------
theme: minima
title: subnetspider's Blog
author: subnetspider
lang: en
icon: 😈

#--------------------------------------------------
# Social Media
#--------------------------------------------------
github_username: subnetspider
twitter_username: subnetspider

#--------------------------------------------------
# General options
#--------------------------------------------------
#url-pretty: "subnetspider.com"

exclude:
  - CNAME
  - LICENSE
  - README.md
